sudo: false
cache: pip

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml
      - wkhtmltopdf # for odoo pdf reports
      - python-ldap # for auth_ldap
      - nodejs
      - npm

language: python

python:
  - '2.7'

virtualenv:
  system_site_packages: true

env:
  matrix:
  - LINT_CHECK="1"
  - EXCLUDE="excel_report_for_stock_valuation,pos_membership" TESTS="1" ODOO_REPO="odoo/odoo"
  - EXCLUDE="excel_report_for_stock_valuation,pos_membership" TESTS="1" ODOO_REPO="OCA/OCB"
  global:
  - VERSION="10.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"

install:
  - git clone --depth=1 https://github.com/Elico-Corp/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - pip install --upgrade pycrypto
  - pip install docxtpl erppeek captcha simple-crypt python-ldap Pillow
  - npm install -g less less-plugin-clean-css

services:
  - postgresql

script:
  - travis_run_tests

after_success:
  - travis_after_test_success
